In [2]:
import pandas as pd
import numpy as np
import os
import glob
import warnings
warnings.filterwarnings('ignore', category=FutureWarning)
pd.set_option('display.max_columns',500)
pd.set_option('display.max_rows',500)
pd.set_option('display.width',1000)

In [4]:
folder_path = r'D:\T100_SEGMENT_US'
file_format = os.path.join(folder_path,"*_T100_SEGMENT_US_CARRIER_ONLY.csv")
file_path = glob.glob(file_format)
dfs = []
for file in file_path:
    print(file)
    read_file = pd.read_csv(file,low_memory=False)
    dfs.append(read_file)
if dfs:
    df = pd.concat(dfs,ignore_index=True)
    print(df.head(3))

D:\T100_SEGMENT_US\2020_T100_SEGMENT_US_CARRIER_ONLY.csv
D:\T100_SEGMENT_US\2021_T100_SEGMENT_US_CARRIER_ONLY.csv
D:\T100_SEGMENT_US\2022_T100_SEGMENT_US_CARRIER_ONLY.csv
D:\T100_SEGMENT_US\2023_T100_SEGMENT_US_CARRIER_ONLY.csv
D:\T100_SEGMENT_US\2024_T100_SEGMENT_US_CARRIER_ONLY.csv
   DEPARTURES_SCHEDULED  DEPARTURES_PERFORMED  PAYLOAD  SEATS  PASSENGERS  FREIGHT  MAIL  DISTANCE  RAMP_TO_RAMP  AIR_TIME UNIQUE_CARRIER  AIRLINE_ID UNIQUE_CARRIER_NAME UNIQUE_CARRIER_ENTITY REGION CARRIER  CARRIER_NAME  CARRIER_GROUP  CARRIER_GROUP_NEW  ORIGIN_AIRPORT_ID  ORIGIN_AIRPORT_SEQ_ID  ORIGIN_CITY_MARKET_ID ORIGIN ORIGIN_CITY_NAME ORIGIN_STATE_ABR  ORIGIN_STATE_FIPS ORIGIN_STATE_NM ORIGIN_COUNTRY ORIGIN_COUNTRY_NAME  ORIGIN_WAC  DEST_AIRPORT_ID  DEST_AIRPORT_SEQ_ID  DEST_CITY_MARKET_ID DEST DEST_CITY_NAME DEST_STATE_ABR  DEST_STATE_FIPS  DEST_STATE_NM DEST_COUNTRY DEST_COUNTRY_NAME  DEST_WAC  AIRCRAFT_GROUP  AIRCRAFT_TYPE  AIRCRAFT_CONFIG  YEAR  QUARTER  MONTH  DISTANCE_GROUP CLASS DATA_SOURCE
0                   0.0                   0.0      0.0    0.0         0.0      0.0   0.0       0.0           0.0       0.0             4B     21599.0        Boutique Air                 01177      D      4B  Boutique Air              1                6.0              10721                1072102                  30721    BOS       Boston, MA               MA               25.0   Massachusetts             US       United States          13            10721              1072102                30721  BOS     Boston, MA             MA             25.0  Massachusetts           US     United States        13               4            479                1  2020        2      6               1     F          DU
1                   0.0                   0.0      0.0    0.0         0.0      0.0   0.0       0.0           0.0       0.0             4B     21599.0        Boutique Air                 01177      D      4B  Boutique Air              1                6.0              10721                1072102                  30721    BOS       Boston, MA               MA               25.0   Massachusetts             US       United States          13            10721              1072102                30721  BOS     Boston, MA             MA             25.0  Massachusetts           US     United States        13               4            479                1  2020        3      9               1     F          DU
2                   0.0                   0.0      0.0    0.0         0.0      0.0   0.0       0.0           0.0       0.0             4B     21599.0        Boutique Air                 01177      D      4B  Boutique Air              1                6.0              10950                1095002                  30950    CEZ       Cortez, CO               CO                8.0        Colorado             US       United States          82            10950              1095002                30950  CEZ     Cortez, CO             CO              8.0       Colorado           US     United States        82               4            479                1  2020        2      6               1     F          DU

In [3]:
df.isna().sum()

DEPARTURES_SCHEDULED          0
DEPARTURES_PERFORMED          0
PAYLOAD                       0
SEATS                         0
PASSENGERS                    0
FREIGHT                       0
MAIL                          0
DISTANCE                      0
RAMP_TO_RAMP                  0
AIR_TIME                      0
UNIQUE_CARRIER               24
AIRLINE_ID                   24
UNIQUE_CARRIER_NAME          24
UNIQUE_CARRIER_ENTITY        24
REGION                       24
CARRIER                       0
CARRIER_NAME                 24
CARRIER_GROUP                 0
CARRIER_GROUP_NEW            24
ORIGIN_AIRPORT_ID             0
ORIGIN_AIRPORT_SEQ_ID         0
ORIGIN_CITY_MARKET_ID         0
ORIGIN                        0
ORIGIN_CITY_NAME              6
ORIGIN_STATE_ABR         112699
ORIGIN_STATE_FIPS        125125
ORIGIN_STATE_NM          112699
ORIGIN_COUNTRY                0
ORIGIN_COUNTRY_NAME           0
ORIGIN_WAC                    0
DEST_AIRPORT_ID               0
DEST_AIRPORT_SEQ_ID           0
DEST_CITY_MARKET_ID           0
DEST                          0
DEST_CITY_NAME                6
DEST_STATE_ABR           111527
DEST_STATE_FIPS          123737
DEST_STATE_NM            111527
DEST_COUNTRY                  0
DEST_COUNTRY_NAME             0
DEST_WAC                      0
AIRCRAFT_GROUP                0
AIRCRAFT_TYPE                 0
AIRCRAFT_CONFIG               0
YEAR                          0
QUARTER                       0
MONTH                         0
DISTANCE_GROUP                0
CLASS                         0
DATA_SOURCE                   0
dtype: int64

In [4]:
df[df['UNIQUE_CARRIER'].isna()]

         DEPARTURES_SCHEDULED  DEPARTURES_PERFORMED   PAYLOAD  SEATS  PASSENGERS  FREIGHT  MAIL  DISTANCE  RAMP_TO_RAMP  AIR_TIME UNIQUE_CARRIER  AIRLINE_ID UNIQUE_CARRIER_NAME UNIQUE_CARRIER_ENTITY REGION CARRIER CARRIER_NAME  CARRIER_GROUP  CARRIER_GROUP_NEW  ORIGIN_AIRPORT_ID  ORIGIN_AIRPORT_SEQ_ID  ORIGIN_CITY_MARKET_ID ORIGIN ORIGIN_CITY_NAME ORIGIN_STATE_ABR  ORIGIN_STATE_FIPS ORIGIN_STATE_NM ORIGIN_COUNTRY ORIGIN_COUNTRY_NAME  ORIGIN_WAC  DEST_AIRPORT_ID  DEST_AIRPORT_SEQ_ID  DEST_CITY_MARKET_ID DEST DEST_CITY_NAME DEST_STATE_ABR  DEST_STATE_FIPS DEST_STATE_NM DEST_COUNTRY DEST_COUNTRY_NAME  DEST_WAC  AIRCRAFT_GROUP  AIRCRAFT_TYPE  AIRCRAFT_CONFIG  YEAR  QUARTER  MONTH  DISTANCE_GROUP CLASS DATA_SOURCE
1075769                  22.0                  15.0   57000.0  120.0        75.0      0.0   0.0     223.0        1640.0    1443.0            NaN         NaN                 NaN                   NaN    NaN      3E          NaN              6                NaN              10693                1069302                  30693    BNA    Nashville, TN               TN               47.0       Tennessee             US       United States          54            12455              1245502                32455  JBR  Jonesboro, AR             AR              5.0      Arkansas           US     United States        71               4            415                1  2022        4     11               1     F          DU
1075770                  22.0                  15.0   57000.0  120.0        80.0      0.0   0.0     223.0        1864.0    1598.0            NaN         NaN                 NaN                   NaN    NaN      3E          NaN              6                NaN              12455                1245502                  32455    JBR    Jonesboro, AR               AR                5.0        Arkansas             US       United States          71            10693              1069302                30693  BNA  Nashville, TN             TN             47.0     Tennessee           US     United States        54               4            415                1  2022        4     11               1     F          DU
1080326                  23.0                  18.0   63000.0  144.0        68.0      0.0   0.0     223.0        1907.0    1701.0            NaN         NaN                 NaN                   NaN    NaN      3E          NaN              6                NaN              10693                1069302                  30693    BNA    Nashville, TN               TN               47.0       Tennessee             US       United States          54            12455              1245502                32455  JBR  Jonesboro, AR             AR              5.0      Arkansas           US     United States        71               4            415                1  2022        4     12               1     F          DU
1080327                  23.0                  18.0   63000.0  144.0        83.0      0.0   0.0     223.0        1604.0    1403.0            NaN         NaN                 NaN                   NaN    NaN      3E          NaN              6                NaN              12455                1245502                  32455    JBR    Jonesboro, AR               AR                5.0        Arkansas             US       United States          71            10693              1069302                30693  BNA  Nashville, TN             TN             47.0     Tennessee           US     United States        54               4            415                1  2022        4     12               1     F          DU
1095299                  26.0                  26.0   98800.0  208.0       115.0      0.0   0.0     223.0        2404.0    2160.0            NaN         NaN                 NaN                   NaN    NaN      3E          NaN              6                NaN              12455                1245502                  32455    JBR    Jonesboro, AR               AR                5.0        Arkansas             US       United States          71            10693              1069302                30693  BNA  Nashville, TN             TN             47.0     Tennessee           US     United States        54               4            415                1  2022        3      9               1     F          DU
1095300                  26.0                  26.0   98800.0  208.0       115.0      0.0   0.0     223.0        2444.0    2150.0            NaN         NaN                 NaN                   NaN    NaN      3E          NaN              6                NaN              10693                1069302                  30693    BNA    Nashville, TN               TN               47.0       Tennessee             US       United States          54            12455              1245502                32455  JBR  Jonesboro, AR             AR              5.0      Arkansas           US     United States        71               4            415                1  2022        3      8               1     F          DU
1095301                  26.0                  26.0   98800.0  208.0       118.0      0.0   0.0     223.0        2390.0    2089.0            NaN         NaN                 NaN                   NaN    NaN      3E          NaN              6                NaN              10693                1069302                  30693    BNA    Nashville, TN               TN               47.0       Tennessee             US       United States          54            12455              1245502                32455  JBR  Jonesboro, AR             AR              5.0      Arkansas           US     United States        71               4            415                1  2022        3      9               1     F          DU
1095303                  26.0                  26.0   98800.0  208.0       132.0      0.0   0.0     223.0        2402.0    2190.0            NaN         NaN                 NaN                   NaN    NaN      3E          NaN              6                NaN              12455                1245502                  32455    JBR    Jonesboro, AR               AR                5.0        Arkansas             US       United States          71            10693              1069302                30693  BNA  Nashville, TN             TN             47.0     Tennessee           US     United States        54               4            415                1  2022        3      8               1     F          DU
1100096                  27.0                  26.0   98800.0  208.0       121.0      0.0   0.0     223.0        2468.0    2161.0            NaN         NaN                 NaN                   NaN    NaN      3E          NaN              6                NaN              10693                1069302                  30693    BNA    Nashville, TN               TN               47.0       Tennessee             US       United States          54            12455              1245502                32455  JBR  Jonesboro, AR             AR              5.0      Arkansas           US     United States        71               4            415                1  2022        4     10               1     F          DU
1100097                  27.0                  26.0   98800.0  208.0       130.0      0.0   0.0     223.0        4280.0    3866.0            NaN         NaN                 NaN                   NaN    NaN      3E          NaN              6                NaN              12455                1245502                  32455    JBR    Jonesboro, AR               AR                5.0        Arkansas             US       United States          71            10693              1069302                30693  BNA  Nashville, TN             TN             47.0     Tennessee           US     United States        54               4            415                1  2022        4     10               1     F          DU
1101175                  27.0                  27.0  102600.0  146.0       144.0      0.0   0.0     223.0        4398.0    2274.0            NaN         NaN                 NaN                   NaN    NaN      3E          NaN              6                NaN              10693                1069302                  30693    BNA    Nashville, TN               TN               47.0       Tennessee             US       United States          54            12455              1245502                32455  JBR  Jonesboro, AR             AR              5.0      Arkansas           US     United States        71               4            415                1  2022        3      7               1     F          DU
1101176                  27.0                  27.0  102600.0  166.0       149.0      0.0   0.0     223.0        2491.0    2219.0            NaN         NaN                 NaN                   NaN    NaN      3E          NaN              6                NaN              12455                1245502                  32455    JBR    Jonesboro, AR               AR                5.0        Arkansas             US       United States          71            10693              1069302                30693  BNA  Nashville, TN             TN             47.0     Tennessee           US     United States        54               4            415                1  2022        3      7               1     F          DU
1165934                  51.0                  17.0   64600.0  136.0        64.0      0.0   0.0     202.0        1434.0    1263.0            NaN         NaN                 NaN                   NaN    NaN      3E          NaN              6                NaN              12455                1245502                  32455    JBR    Jonesboro, AR               AR                5.0        Arkansas             US       United States          71            15016              1501606                31123  STL  St. Louis, MO             MO             29.0      Missouri           US     United States        64               4            415                1  2022        4     11               1     F          DU
1165935                  51.0                  17.0   64600.0  136.0        66.0      0.0   0.0     202.0        1590.0    1382.0            NaN         NaN                 NaN                   NaN    NaN      3E          NaN              6                NaN              15016                1501606                  31123    STL    St. Louis, MO               MO               29.0        Missouri             US       United States          64            12455              1245502                32455  JBR  Jonesboro, AR             AR              5.0      Arkansas           US     United States        71               4            415                1  2022        4     11               1     F          DU
1167309                  52.0                  42.0  159600.0  336.0       143.0      0.0   0.0     202.0        3472.0    3038.0            NaN         NaN                 NaN                   NaN    NaN      3E          NaN              6                NaN              12455                1245502                  32455    JBR    Jonesboro, AR               AR                5.0        Arkansas             US       United States          71            15016              1501606                31123  STL  St. Louis, MO             MO             29.0      Missouri           US     United States        64               4            415                1  2022        4     10               1     F          DU
1167532                  52.0                  49.0  186200.0  392.0       192.0      0.0   0.0     202.0        4041.0    3534.0            NaN         NaN                 NaN                   NaN    NaN      3E          NaN              6                NaN              15016                1501606                  31123    STL    St. Louis, MO               MO               29.0        Missouri             US       United States          64            12455              1245502                32455  JBR  Jonesboro, AR             AR              5.0      Arkansas           US     United States        71               4            415                1  2022        3      9               1     F          DU
1167534                  52.0                  49.0  186200.0  392.0       205.0      0.0   0.0     202.0        4319.0    3727.0            NaN         NaN                 NaN                   NaN    NaN      3E          NaN              6                NaN              12455                1245502                  32455    JBR    Jonesboro, AR               AR                5.0        Arkansas             US       United States          71            15016              1501606                31123  STL  St. Louis, MO             MO             29.0      Missouri           US     United States        64               4            415                1  2022        3      9               1     F          DU
1168134                  52.0                  52.0  197600.0  416.0       141.0      0.0   0.0     202.0        3429.0    3043.0            NaN         NaN                 NaN                   NaN    NaN      3E          NaN              6                NaN              15016                1501606                  31123    STL    St. Louis, MO               MO               29.0        Missouri             US       United States          64            12455              1245502                32455  JBR  Jonesboro, AR             AR              5.0      Arkansas           US     United States        71               4            415                1  2022        4     10               1     F          DU
1168136                  52.0                  52.0  197600.0  416.0       234.0      0.0   0.0     202.0        4564.0    3971.0            NaN         NaN                 NaN                   NaN    NaN      3E          NaN              6                NaN              15016                1501606                  31123    STL    St. Louis, MO               MO               29.0        Missouri             US       United States          64            12455              1245502                32455  JBR  Jonesboro, AR             AR              5.0      Arkansas           US     United States        71               4            415                1  2022        3      7               1     F          DU
1168138                  52.0                  52.0  197600.0  416.0       272.0      0.0   0.0     202.0        4437.0    3841.0            NaN         NaN                 NaN                   NaN    NaN      3E          NaN              6                NaN              12455                1245502                  32455    JBR    Jonesboro, AR               AR                5.0        Arkansas             US       United States          71            15016              1501606                31123  STL  St. Louis, MO             MO             29.0      Missouri           US     United States        64               4            415                1  2022        3      7               1     F          DU
1170277                  54.0                  18.0   63000.0  144.0        65.0      0.0   0.0     202.0        1750.0    1532.0            NaN         NaN                 NaN                   NaN    NaN      3E          NaN              6                NaN              15016                1501606                  31123    STL    St. Louis, MO               MO               29.0        Missouri             US       United States          64            12455              1245502                32455  JBR  Jonesboro, AR             AR              5.0      Arkansas           US     United States        71               4            415                1  2022        4     12               1     F          DU
1170278                  54.0                  18.0   63000.0  144.0        69.0      0.0   0.0     202.0        1559.0    1356.0            NaN         NaN                 NaN                   NaN    NaN      3E          NaN              6                NaN              12455                1245502                  32455    JBR    Jonesboro, AR               AR                5.0        Arkansas             US       United States          71            15016              1501606                31123  STL  St. Louis, MO             MO             29.0      Missouri           US     United States        64               4            415                1  2022        4     12               1     F          DU
1171124                  54.0                  54.0  205200.0  432.0       215.0      0.0   0.0     202.0        4537.0    3996.0            NaN         NaN                 NaN                   NaN    NaN      3E          NaN              6                NaN              15016                1501606                  31123    STL    St. Louis, MO               MO               29.0        Missouri             US       United States          64            12455              1245502                32455  JBR  Jonesboro, AR             AR              5.0      Arkansas           US     United States        71               4            415                1  2022        3      8               1     F          DU
1171126                  54.0                  54.0  205200.0  432.0       253.0      0.0   0.0     202.0        5196.0    4723.0            NaN         NaN                 NaN                   NaN    NaN      3E          NaN              6                NaN              12455                1245502                  32455    JBR    Jonesboro, AR               AR                5.0        Arkansas             US       United States          71            15016              1501606                31123  STL  St. Louis, MO             MO             29.0      Missouri           US     United States        64               4            415                1  2022        3      8               1     F          DU

In [5]:
df.dropna(subset='UNIQUE_CARRIER',inplace=True)
df.isna().sum()

DEPARTURES_SCHEDULED          0
DEPARTURES_PERFORMED          0
PAYLOAD                       0
SEATS                         0
PASSENGERS                    0
FREIGHT                       0
MAIL                          0
DISTANCE                      0
RAMP_TO_RAMP                  0
AIR_TIME                      0
UNIQUE_CARRIER                0
AIRLINE_ID                    0
UNIQUE_CARRIER_NAME           0
UNIQUE_CARRIER_ENTITY         0
REGION                        0
CARRIER                       0
CARRIER_NAME                  0
CARRIER_GROUP                 0
CARRIER_GROUP_NEW             0
ORIGIN_AIRPORT_ID             0
ORIGIN_AIRPORT_SEQ_ID         0
ORIGIN_CITY_MARKET_ID         0
ORIGIN                        0
ORIGIN_CITY_NAME              6
ORIGIN_STATE_ABR         112699
ORIGIN_STATE_FIPS        125125
ORIGIN_STATE_NM          112699
ORIGIN_COUNTRY                0
ORIGIN_COUNTRY_NAME           0
ORIGIN_WAC                    0
DEST_AIRPORT_ID               0
DEST_AIRPORT_SEQ_ID           0
DEST_CITY_MARKET_ID           0
DEST                          0
DEST_CITY_NAME                6
DEST_STATE_ABR           111527
DEST_STATE_FIPS          123737
DEST_STATE_NM            111527
DEST_COUNTRY                  0
DEST_COUNTRY_NAME             0
DEST_WAC                      0
AIRCRAFT_GROUP                0
AIRCRAFT_TYPE                 0
AIRCRAFT_CONFIG               0
YEAR                          0
QUARTER                       0
MONTH                         0
DISTANCE_GROUP                0
CLASS                         0
DATA_SOURCE                   0
dtype: int64

In [6]:
df[df['ORIGIN_CITY_NAME'].isna()]

         DEPARTURES_SCHEDULED  DEPARTURES_PERFORMED  PAYLOAD  SEATS  PASSENGERS  FREIGHT  MAIL  DISTANCE  RAMP_TO_RAMP  AIR_TIME UNIQUE_CARRIER  AIRLINE_ID                                UNIQUE_CARRIER_NAME UNIQUE_CARRIER_ENTITY REGION CARRIER                                       CARRIER_NAME  CARRIER_GROUP  CARRIER_GROUP_NEW  ORIGIN_AIRPORT_ID  ORIGIN_AIRPORT_SEQ_ID  ORIGIN_CITY_MARKET_ID ORIGIN ORIGIN_CITY_NAME ORIGIN_STATE_ABR  ORIGIN_STATE_FIPS ORIGIN_STATE_NM ORIGIN_COUNTRY ORIGIN_COUNTRY_NAME  ORIGIN_WAC  DEST_AIRPORT_ID  DEST_AIRPORT_SEQ_ID  DEST_CITY_MARKET_ID DEST        DEST_CITY_NAME DEST_STATE_ABR  DEST_STATE_FIPS DEST_STATE_NM DEST_COUNTRY DEST_COUNTRY_NAME  DEST_WAC  AIRCRAFT_GROUP  AIRCRAFT_TYPE  AIRCRAFT_CONFIG  YEAR  QUARTER  MONTH  DISTANCE_GROUP CLASS DATA_SOURCE
1238707                   0.0                   1.0   5193.0   13.0         0.0      0.0   0.0      43.0          37.0      17.0             LF     21635.0  CFM Inc d/b/a Contour Airlines d/b/a One Jet S...                 01189      D      LF  CFM Inc d/b/a Contour Airlines d/b/a One Jet S...              1                6.0            1138701                1138701                  31387    M91              NaN               TN               47.0       Tennessee             US       United States          54            13461              1346101                33461  MQY            Smyrna, TN             TN             47.0     Tennessee           US     United States        54               6            674                1  2023        4     10               1     L          DU
1238735                   0.0                   1.0   5193.0   13.0         1.0      0.0   0.0      24.0          24.0      12.0             LF     21635.0  CFM Inc d/b/a Contour Airlines d/b/a One Jet S...                 01189      D      LF  CFM Inc d/b/a Contour Airlines d/b/a One Jet S...              1                6.0            1138701                1138701                  31387    M91              NaN               TN               47.0       Tennessee             US       United States          54            12574              1257404                30693  TN8         Nashville, TN             TN             47.0     Tennessee           US     United States        54               6            674                1  2023        4     10               1     L          DU
1238750                   0.0                   1.0   5193.0   13.0         3.0      0.0   0.0     267.0          60.0      48.0             LF     21635.0  CFM Inc d/b/a Contour Airlines d/b/a One Jet S...                 01189      D      LF  CFM Inc d/b/a Contour Airlines d/b/a One Jet S...              1                6.0            1138701                1138701                  31387    M91              NaN               TN               47.0       Tennessee             US       United States          54            12878              1287803                32878  LAF         Lafayette, IN             IN             18.0       Indiana           US     United States        42               6            674                1  2023        4     10               1     L          DU
1238755                   0.0                   1.0   5193.0   13.0         3.0      0.0   0.0    1003.0         170.0     150.0             LF     21635.0  CFM Inc d/b/a Contour Airlines d/b/a One Jet S...                 01189      D      LF  CFM Inc d/b/a Contour Airlines d/b/a One Jet S...              1                6.0            1138701                1138701                  31387    M91              NaN               TN               47.0       Tennessee             US       United States          54            10627              1062702                30627  BIS   Bismarck/Mandan, ND             ND             38.0  North Dakota           US     United States        66               6            674                1  2023        4     10               3     L          DU
1243333                   0.0                   1.0   7500.0   15.0         0.0      0.0   0.0     785.0         134.0     112.0             LF     21635.0  CFM Inc d/b/a Contour Airlines d/b/a One Jet S...                 01189      D      LF  CFM Inc d/b/a Contour Airlines d/b/a One Jet S...              1                6.0            1138701                1138701                  31387    M91              NaN               TN               47.0       Tennessee             US       United States          54            11764              1176405                31764  FRG  East Farmingdale, NY             NY             36.0      New York           US     United States        22               6            669                1  2023        4     10               2     L          DU
1243758                   0.0                   1.0   7500.0   16.0        12.0      0.0   0.0     771.0         155.0     136.0             LF     21635.0  CFM Inc d/b/a Contour Airlines d/b/a One Jet S...                 01189      D      LF  CFM Inc d/b/a Contour Airlines d/b/a One Jet S...              1                6.0            1138701                1138701                  31387    M91              NaN               TN               47.0       Tennessee             US       United States          54            13287              1328702                33287  MHE          Mitchell, SD             SD             46.0  South Dakota           US     United States        67               6            669                1  2023        4     10               2     L          DU

In [7]:
df.loc[(df['ORIGIN'] == 'M91'),'ORIGIN_CITY_NAME'] = 'Springfield, TN'
df.isna().sum()

DEPARTURES_SCHEDULED          0
DEPARTURES_PERFORMED          0
PAYLOAD                       0
SEATS                         0
PASSENGERS                    0
FREIGHT                       0
MAIL                          0
DISTANCE                      0
RAMP_TO_RAMP                  0
AIR_TIME                      0
UNIQUE_CARRIER                0
AIRLINE_ID                    0
UNIQUE_CARRIER_NAME           0
UNIQUE_CARRIER_ENTITY         0
REGION                        0
CARRIER                       0
CARRIER_NAME                  0
CARRIER_GROUP                 0
CARRIER_GROUP_NEW             0
ORIGIN_AIRPORT_ID             0
ORIGIN_AIRPORT_SEQ_ID         0
ORIGIN_CITY_MARKET_ID         0
ORIGIN                        0
ORIGIN_CITY_NAME              0
ORIGIN_STATE_ABR         112699
ORIGIN_STATE_FIPS        125125
ORIGIN_STATE_NM          112699
ORIGIN_COUNTRY                0
ORIGIN_COUNTRY_NAME           0
ORIGIN_WAC                    0
DEST_AIRPORT_ID               0
DEST_AIRPORT_SEQ_ID           0
DEST_CITY_MARKET_ID           0
DEST                          0
DEST_CITY_NAME                6
DEST_STATE_ABR           111527
DEST_STATE_FIPS          123737
DEST_STATE_NM            111527
DEST_COUNTRY                  0
DEST_COUNTRY_NAME             0
DEST_WAC                      0
AIRCRAFT_GROUP                0
AIRCRAFT_TYPE                 0
AIRCRAFT_CONFIG               0
YEAR                          0
QUARTER                       0
MONTH                         0
DISTANCE_GROUP                0
CLASS                         0
DATA_SOURCE                   0
dtype: int64

In [8]:
df = df[df['DEPARTURES_PERFORMED'] > 0]
df.shape

(2190385, 50)

In [9]:
df = df[~((df['SEATS'] == 0) & (df['PASSENGERS'] > 0))]
df.shape

(2189927, 50)

In [10]:
df = df[~((df['AIR_TIME'] == 0) & (df['DISTANCE'] > 0))]
df.shape

(2189770, 50)

In [11]:
df = df[~((df['DISTANCE'] == 0) & (df['AIR_TIME'] > 0))]
df.shape

(2181042, 50)

In [12]:
df['YEAR_MONTH'] = df['YEAR'].astype(str) + df['MONTH'].astype(str).str.zfill(2)
df.head(3)

     DEPARTURES_SCHEDULED  DEPARTURES_PERFORMED  PAYLOAD  SEATS  PASSENGERS  FREIGHT  MAIL  DISTANCE  RAMP_TO_RAMP  AIR_TIME UNIQUE_CARRIER  AIRLINE_ID                                UNIQUE_CARRIER_NAME UNIQUE_CARRIER_ENTITY REGION CARRIER                                       CARRIER_NAME  CARRIER_GROUP  CARRIER_GROUP_NEW  ORIGIN_AIRPORT_ID  ORIGIN_AIRPORT_SEQ_ID  ORIGIN_CITY_MARKET_ID ORIGIN           ORIGIN_CITY_NAME ORIGIN_STATE_ABR  ORIGIN_STATE_FIPS ORIGIN_STATE_NM ORIGIN_COUNTRY ORIGIN_COUNTRY_NAME  ORIGIN_WAC  DEST_AIRPORT_ID  DEST_AIRPORT_SEQ_ID  DEST_CITY_MARKET_ID DEST             DEST_CITY_NAME DEST_STATE_ABR  DEST_STATE_FIPS   DEST_STATE_NM DEST_COUNTRY DEST_COUNTRY_NAME  DEST_WAC  AIRCRAFT_GROUP  AIRCRAFT_TYPE  AIRCRAFT_CONFIG  YEAR  QUARTER  MONTH  DISTANCE_GROUP CLASS DATA_SOURCE YEAR_MONTH
472                   0.0                   1.0      0.0    0.0         0.0      0.0   0.0       0.0          22.0       0.0            09Q     21161.0  Swift Air, LLC d/b/a Eastern Air Lines d/b/a E...                  1130      D     09Q  Swift Air, LLC d/b/a Eastern Air Lines d/b/a E...              2                2.0              11193                1119302                  33105    CVG             Cincinnati, OH               KY               21.0        Kentucky             US       United States          52            11193              1119302                33105  CVG             Cincinnati, OH             KY             21.0        Kentucky           US     United States        52               6            614                1  2020        3      9               1     L          DU     202009
473                   0.0                   1.0      0.0    0.0         0.0      0.0   0.0     330.0          78.0      56.0            09Q     21161.0  Swift Air, LLC d/b/a Eastern Air Lines d/b/a E...                  1130      D     09Q  Swift Air, LLC d/b/a Eastern Air Lines d/b/a E...              2                2.0              11193                1119302                  33105    CVG             Cincinnati, OH               KY               21.0        Kentucky             US       United States          52            11995              1199502                31995  GSO  Greensboro/High Point, NC             NC             37.0  North Carolina           US     United States        36               6            617                1  2020        3      9               1     L          DU     202009
474                   0.0                   1.0      0.0    0.0         0.0      0.0   0.0     330.0          82.0      56.0            09Q     21161.0  Swift Air, LLC d/b/a Eastern Air Lines d/b/a E...                  1130      D     09Q  Swift Air, LLC d/b/a Eastern Air Lines d/b/a E...              2                2.0              11995                1199502                  31995    GSO  Greensboro/High Point, NC               NC               37.0  North Carolina             US       United States          36            11193              1119302                33105  CVG             Cincinnati, OH             KY             21.0        Kentucky           US     United States        52               6            617                1  2020        3      9               1     L          DU     202009

In [13]:
df['Route_flight'] = df['ORIGIN'].astype(str) + ' - ' + df['DEST'].astype(str)
df.head(3)

     DEPARTURES_SCHEDULED  DEPARTURES_PERFORMED  PAYLOAD  SEATS  PASSENGERS  FREIGHT  MAIL  DISTANCE  RAMP_TO_RAMP  AIR_TIME UNIQUE_CARRIER  AIRLINE_ID                                UNIQUE_CARRIER_NAME UNIQUE_CARRIER_ENTITY REGION CARRIER                                       CARRIER_NAME  CARRIER_GROUP  CARRIER_GROUP_NEW  ORIGIN_AIRPORT_ID  ORIGIN_AIRPORT_SEQ_ID  ORIGIN_CITY_MARKET_ID ORIGIN           ORIGIN_CITY_NAME ORIGIN_STATE_ABR  ORIGIN_STATE_FIPS ORIGIN_STATE_NM ORIGIN_COUNTRY ORIGIN_COUNTRY_NAME  ORIGIN_WAC  DEST_AIRPORT_ID  DEST_AIRPORT_SEQ_ID  DEST_CITY_MARKET_ID DEST             DEST_CITY_NAME DEST_STATE_ABR  DEST_STATE_FIPS   DEST_STATE_NM DEST_COUNTRY DEST_COUNTRY_NAME  DEST_WAC  AIRCRAFT_GROUP  AIRCRAFT_TYPE  AIRCRAFT_CONFIG  YEAR  QUARTER  MONTH  DISTANCE_GROUP CLASS DATA_SOURCE YEAR_MONTH Route_flight
472                   0.0                   1.0      0.0    0.0         0.0      0.0   0.0       0.0          22.0       0.0            09Q     21161.0  Swift Air, LLC d/b/a Eastern Air Lines d/b/a E...                  1130      D     09Q  Swift Air, LLC d/b/a Eastern Air Lines d/b/a E...              2                2.0              11193                1119302                  33105    CVG             Cincinnati, OH               KY               21.0        Kentucky             US       United States          52            11193              1119302                33105  CVG             Cincinnati, OH             KY             21.0        Kentucky           US     United States        52               6            614                1  2020        3      9               1     L          DU     202009    CVG - CVG
473                   0.0                   1.0      0.0    0.0         0.0      0.0   0.0     330.0          78.0      56.0            09Q     21161.0  Swift Air, LLC d/b/a Eastern Air Lines d/b/a E...                  1130      D     09Q  Swift Air, LLC d/b/a Eastern Air Lines d/b/a E...              2                2.0              11193                1119302                  33105    CVG             Cincinnati, OH               KY               21.0        Kentucky             US       United States          52            11995              1199502                31995  GSO  Greensboro/High Point, NC             NC             37.0  North Carolina           US     United States        36               6            617                1  2020        3      9               1     L          DU     202009    CVG - GSO
474                   0.0                   1.0      0.0    0.0         0.0      0.0   0.0     330.0          82.0      56.0            09Q     21161.0  Swift Air, LLC d/b/a Eastern Air Lines d/b/a E...                  1130      D     09Q  Swift Air, LLC d/b/a Eastern Air Lines d/b/a E...              2                2.0              11995                1199502                  31995    GSO  Greensboro/High Point, NC               NC               37.0  North Carolina             US       United States          36            11193              1119302                33105  CVG             Cincinnati, OH             KY             21.0        Kentucky           US     United States        52               6            617                1  2020        3      9               1     L          DU     202009    GSO - CVG

In [14]:
df = df[~(df['AIR_TIME']> df['RAMP_TO_RAMP'])]
df.shape

(2181040, 52)

In [15]:
Fact_US_Carrier = df[['DEPARTURES_SCHEDULED','DEPARTURES_PERFORMED','PAYLOAD','SEATS','PASSENGERS','FREIGHT','MAIL','DISTANCE','RAMP_TO_RAMP','AIR_TIME','UNIQUE_CARRIER','CARRIER_GROUP','ORIGIN_AIRPORT_ID','DEST_AIRPORT_ID','AIRCRAFT_TYPE','AIRCRAFT_GROUP','YEAR_MONTH','Route_flight']]
Fact_US_Carrier.columns = ['Departures_Schedule','Departures_Performed','Payload','Seats','Passengers','Freight','Mail','Distance','Ramp_to_Ramp','Air_Time','Carrier_ID','Carrier_Group_ID','Origin_Airport_ID','Dest_Airport_ID','Aircraft_Type','Aircraft_Group','Date_ID','Route_flight']
Fact_US_Carrier.head(5)

     Departures_Schedule  Departures_Performed  Payload  Seats  Passengers  Freight  Mail  Distance  Ramp_to_Ramp  Air_Time Carrier_ID  Carrier_Group_ID  Origin_Airport_ID  Dest_Airport_ID  Aircraft_Type  Aircraft_Group Date_ID Route_flight
472                  0.0                   1.0      0.0    0.0         0.0      0.0   0.0       0.0          22.0       0.0        09Q                 2              11193            11193            614               6  202009    CVG - CVG
473                  0.0                   1.0      0.0    0.0         0.0      0.0   0.0     330.0          78.0      56.0        09Q                 2              11193            11995            617               6  202009    CVG - GSO
474                  0.0                   1.0      0.0    0.0         0.0      0.0   0.0     330.0          82.0      56.0        09Q                 2              11995            11193            617               6  202009    GSO - CVG
475                  0.0                   1.0      0.0    0.0         0.0      0.0   0.0     391.0          83.0      64.0        09Q                 2              14570            12892            614               6  202009    RNO - LAX
476                  0.0                   1.0      0.0    0.0         0.0      0.0   0.0     589.0         113.0      92.0        09Q                 2              11193            12478            617               6  202009    CVG - JFK

In [16]:
Dim_Date = df[['YEAR_MONTH','YEAR','MONTH']].drop_duplicates().sort_values(by=['YEAR', 'MONTH'], ascending=[True, True]).reset_index(drop=True)
Dim_Date.columns = ['Date_ID','Year','Month_num']
Dim_Date.head(5)

  Date_ID  Year  Month_num
0  202001  2020          1
1  202002  2020          2
2  202003  2020          3
3  202004  2020          4
4  202005  2020          5

In [16]:
month_map = {
    1: 'Jan', 2: 'Feb', 3: 'Mar', 4: 'Apr',
    5: 'May', 6: 'Jun', 7: 'Jul', 8: 'Aug',
    9: 'Sep', 10: 'Oct', 11: 'Nov', 12: 'Dec'
}

Dim_Date['Month'] = Dim_Date['Month_num'].map(month_map)
Dim_Date.head(12)

   Date_ID  Year  Month_num Month
0   202001  2020          1   Jan
1   202002  2020          2   Feb
2   202003  2020          3   Mar
3   202004  2020          4   Apr
4   202005  2020          5   May
5   202006  2020          6   Jun
6   202007  2020          7   Jul
7   202008  2020          8   Aug
8   202009  2020          9   Sep
9   202010  2020         10   Oct
10  202011  2020         11   Nov
11  202012  2020         12   Dec

In [17]:
Dim_Carrier = df[['UNIQUE_CARRIER','UNIQUE_CARRIER_NAME']].drop_duplicates().sort_values(by='UNIQUE_CARRIER_NAME', ascending=True).reset_index(drop=True)
Dim_Carrier.columns = ['Carrier_ID','Carrier_Name']
Dim_Carrier.head(5)

  Carrier_ID                         Carrier_Name
0         Q5                          40-Mile Air
1        ABX                          ABX Air Inc
2         AN                    ADVANCED AIR, LLC
3        1YQ  Air Charter, Inc d/b/a Air Flamenco
4         X4                   Air Excursions LLC

In [17]:
origin = df[['ORIGIN_AIRPORT_ID','ORIGIN','ORIGIN_CITY_NAME','ORIGIN_STATE_ABR','ORIGIN_STATE_NM','ORIGIN_COUNTRY','ORIGIN_COUNTRY_NAME']]\
            .drop_duplicates(subset='ORIGIN_AIRPORT_ID')\
            .sort_values(by='ORIGIN_AIRPORT_ID', ascending=True)\
            .reset_index(drop=True)
origin.columns = ['Airport_ID','Airport_code','City_Name','State_ABR','State_Name','Country_ABR','Country']
origin.head(5)

   Airport_ID Airport_code         City_Name State_ABR State_Name Country_ABR        Country
0       10001          01A  Afognak Lake, AK        AK     Alaska          US  United States
1       10005          05A  Little Squaw, AK        AK     Alaska          US  United States
2       10006          06A      Kizhuyak, AK        AK     Alaska          US  United States
3       10009          09A         Homer, AK        AK     Alaska          US  United States
4       10010          1B1        Hudson, NY        NY   New York          US  United States

In [18]:
dest = df[['DEST_AIRPORT_ID','DEST','DEST_CITY_NAME','DEST_STATE_ABR','DEST_STATE_NM','DEST_COUNTRY','DEST_COUNTRY_NAME']] \
            .drop_duplicates(subset='DEST_AIRPORT_ID') \
            .sort_values(by='DEST_AIRPORT_ID', ascending=True) \
            .reset_index(drop=True)
dest.columns = ['Airport_ID','Airport_code','City_Name','State_ABR','State_Name','Country_ABR','Country']
dest.head(5)

   Airport_ID Airport_code         City_Name State_ABR State_Name Country_ABR        Country
0       10001          01A  Afognak Lake, AK        AK     Alaska          US  United States
1       10005          05A  Little Squaw, AK        AK     Alaska          US  United States
2       10006          06A      Kizhuyak, AK        AK     Alaska          US  United States
3       10009          09A         Homer, AK        AK     Alaska          US  United States
4       10010          1B1        Hudson, NY        NY   New York          US  United States

In [19]:
Dim_Airport = pd.concat([origin,dest],axis=0, ignore_index=True)
Dim_Airport.head(5)

   Airport_ID Airport_code         City_Name State_ABR State_Name Country_ABR        Country
0       10001          01A  Afognak Lake, AK        AK     Alaska          US  United States
1       10005          05A  Little Squaw, AK        AK     Alaska          US  United States
2       10006          06A      Kizhuyak, AK        AK     Alaska          US  United States
3       10009          09A         Homer, AK        AK     Alaska          US  United States
4       10010          1B1        Hudson, NY        NY   New York          US  United States

In [20]:
Dim_Airport = Dim_Airport.drop_duplicates(subset='Airport_ID').reset_index(drop=True)
Dim_Airport.shape

(2468, 7)

In [21]:
Dim_Airport.isna().sum()

Airport_ID        0
Airport_code      0
City_Name         0
State_ABR       552
State_Name      552
Country_ABR       0
Country           0
dtype: int64

In [22]:
Dim_Airport[Dim_Airport['State_ABR'].isna()].head(5)

    Airport_ID Airport_code                 City_Name State_ABR State_Name Country_ABR         Country
43       10147          ABZ  Aberdeen, United Kingdom       NaN        NaN          GB  United Kingdom
44       10148          ACA          Acapulco, Mexico       NaN        NaN          MX          Mexico
45       10150          ACC              Accra, Ghana       NaN        NaN          GH           Ghana
50       10164          ADJ             Amman, Jordan       NaN        NaN          JO          Jordan
52       10166          ADL       Adelaide, Australia       NaN        NaN          AU       Australia

In [23]:
Dim_Airport[['State_ABR','State_Name']] = Dim_Airport[['State_ABR','State_Name']].fillna('Outside of US')
Dim_Airport.isna().sum()

Airport_ID      0
Airport_code    0
City_Name       0
State_ABR       0
State_Name      0
Country_ABR     0
Country         0
dtype: int64

In [ ]:
Dim_Aircraft = pd.read_csv('AIRCRAFT_TYPE.csv')
Dim_Aircraft.columns = ['Aircraft_Type','Aircraft_Name']
Dim_Aircraft.head(5)

   Aircraft_Type                              Aircraft_Name
0              7                         Aero Commander 200
1              8                          Aero Macchi AL-60
2              9                               Aeronca 7-AC
3             10  Beech Bonanza 35A/C/D/E/G/H/J/K/S/V/  36A
4             20                            Bellanca CH-300